-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  ven. 12 juin 2020 à 14:14
-- Version du serveur :  5.7.26
-- Version de PHP :  7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `food_substitue_bdd`
--

-- --------------------------------------------------------

--
-- Structure de la table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` text NOT NULL,
  `product_name` varchar(150) NOT NULL,
  `ingredients_text` text NOT NULL,
  `nutrition_grade` text NOT NULL,
  `stores` text NOT NULL,
  `brands` text NOT NULL,
  `link` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_name` (`product_name`)
) ENGINE=MyISAM AUTO_INCREMENT=158 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `products`
--

INSERT INTO `products` (`id`, `category`, `product_name`, `ingredients_text`, `nutrition_grade`, `stores`, `brands`, `link`) VALUES
(1, 'pizzas', 'Pizza Chorizo', 'farine de _blé_ (_gluten_), _mozzarella_ (_lait_) 25%, purée de tomate, chorizo choix 12,5% (viande de porc, gras de porc, sel, épices, dextrose, antioxydant : extraits de romarin, conservateur : nitrite de sodium, fumée),  eau, huile d\'olive vierge extra, sel, dextrose, levure de boulangerie, huile de colza, amidon, amidon de _blé_ (_gluten_), sucre, origan', 'd', 'Thiriet', 'Thiriet', 'https://fr.openfoodfacts.org/produit/3292590824914/pizza-chorizo-thiriet'),
(2, 'pizzas', 'Pizza Merveillosa mozzarella', 'Garniture 58,2% : mozzarella (lait) 21%, purée de tomates reconstituée 20%, edam (lait) 4,9%, tomates 4,4%, huile d\'olive, eau, épices et plantes aromatiques, épinards 0,8%, huile de colza, sucre, farine de blé, sel, amidons de pomme de terre et de blé, protéines de blé.\r\n\r\nPâte cuite 41,8% : farine de blé, eau, huile de colza, levure, sel, sucre. \r\n\r\nTraces de céleri.\r\n\r\nLes pourcentages sont exprimés sur le produit total.', 'c', 'Leclerc', 'Volpone,Marque Repère,Turini', 'https://fr.openfoodfacts.org/produit/3564700594957/pizza-merveillosa-mozzarella-volpone'),
(3, 'pizzas', 'Pizza Mozzarella Ristorante', '21% purée de tomate, 19% _fromage_ Mozzarella, farine de riz, eau, amidon de pomme de terre, 7,8% tomates cerises, _fromage_ Edam, flocons de pommes de terre, huile de colza, protéines de pois, herbes aromatiques, levure de boulangerie, sucre, sel, épaississants (hydroxypropylméthylcellulose, gomme xanthane), huile d\'olive vierge extra, épinards, amidon modifié, ail, émulsifiants (esters lactiques des mono - et diglycérides d\'acides gras, esters acétiques des mono-et diglycérides d\'acides gras, mono - et diglycérides d\'acides gras), épices, sirop de glucose, jus de citron, _lait_ écrémé en poudre, dextrose. Convient aux végétariens.', 'c', 'Coop Konsum,Delhaize', 'Dr. Oetker', 'https://fr.openfoodfacts.org/produit/4001724022398/pizza-mozzarella-ristorante-dr-oetker'),
(4, 'pizzas', 'Pizza calzone fromages et jambon', '', 'c', '', '', 'https://fr.openfoodfacts.org/produit/26045702/pizza-calzone-fromages-et-jambon'),
(5, 'pizzas', 'Pizza 3 fromages cuite au feu de bois', 'Garniture 57% : mozzarella (lait) (dont correcteur d\'acidité : acide citrique) 21,9%, purée de tomates 21%, Pecorino Romano (lait) 3,7%, eau, olives noires (olives, sel) 2,8%, Gorgonzola (lait) 2,2%, oignons, huile d\'olive, épices et plantes aromatiques, sucre, sel.\nPâte 43% : farine de blé, eau, huile de tournesol, levure, sel.\nLes pourcentages sont exprimés sur le produit total.', 'b', 'Leclerc', 'Turini,Marque Repère', 'https://fr.openfoodfacts.org/produit/3564700405703/pizza-3-fromages-cuite-au-feu-de-bois-turini'),
(6, 'pizzas', 'Pizza jambon cuit et mini mozzarella (BIO)', '', 'c', '', '', 'https://fr.openfoodfacts.org/produit/3664042002483/pizza-jambon-cuit-et-mini-mozzarella-bio'),
(7, 'pizzas', 'Ristorante: Pizza spinaci', 'Farine de BLE, 24% purée de tomate, 20% épinards, 14% FROMAGE (MOZZARELLA, EDAM), huile de colza, eau, levure de boulangerie, sel, sucre, amidon modifié, matière grasse de palme, ail, protéines végétales hydrolysées, maltodextrine, poivre de Cayenne, caramel.', 'c', 'Coles,Bilo,Woolworths,Delhaize', 'Dr. Oetker', 'https://fr.openfoodfacts.org/produit/4001724819400/ristorante-pizza-spinaci-dr-oetker'),
(8, 'pizzas', '', '', 'd', '', 'Dr.Oetker', 'https://fr.openfoodfacts.org/produit/4001724628804/pizza-salame-dr-oetker'),
(9, 'pizzas', 'Pizza divina mozzarella', '', 'd', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710455850/pizza-divina-mozzarella-auchan'),
(10, 'pizzas', 'Mini calzone jambon mozzarella', 'Farine de _blé_ (_gluten_), eau, pulpe de tomate 17,6%, jambon cuit 11,8% [viande de porc (origine : UE), eau, sel, amidon de pomme de terre, sucre, dextrose de maïs, épices et extraits d\'épices, antioxydant : ascorbate de sodium, conservateur : nitrite de sodium], mozzarella (contient _lait_ ; UE) 11,8%e semoule de _blé_ dur (_gluten_), sel, huile d\'olive vierge extra, origan, levure.', 'c', 'Picard', 'Picard,Picard', 'https://fr.openfoodfacts.org/produit/3270160890156/mini-calzone-jambon-mozzarella-picard'),
(11, 'pizzas', 'Pizza Kebab', 'Farine de blé, eau, émincé de poulet traité en salaison 14% (viande de poulet 12,8%, eau, fécule, dextrose, sel, épaississant : carraghénanes), mozzarella 14% (lait), fromage blanc (lait), oignons rouges 4,4%, poivrons rouges 3,8%, crème fraîche (lait), oignons, huile de colza, amidon transformé, sel, levure boulangère, épices kebab (épices et aromates, chapelure de blé, tomate, sel, huile de tournesol, extrait d\'épice), sucre, menthe douce ; poudres à lever : diphosphate disodique, carbonate acide de sodium ; amidon de blé, purée de piments (piments, sel, correcteur d\'acidité : acide acétique), cumin, poivre, muscade. Pourcentages exprimés sur le total de la recette. Traces éventuelles de poisson, crustacés, mollusques, œuf, moutarde et céleri.', 'b', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710464562/pizza-kebab-auchan'),
(12, 'pizzas', 'Pizza Burrata et legumes du soleil', 'Farine del BLE*, eau, mozzarella* (LAIT, sel, présure, ferments lactiques, correcteur d\'acidité E330), burrata* (LAIT, créme UHT, sel, présure), courgettes grillés*, poivrons grillés*, sauce tomate*, semoule de BLÉ DUR* sel, levure 0,0003%. \r\n*Produit issu de l\'agriculture biologique', 'c', 'Carrefour', '', 'https://fr.openfoodfacts.org/produit/3664042002667/pizza-burrata-et-legumes-du-soleil'),
(13, 'pizzas', 'Pizza vegetarienne', '', 'c', '', '', 'https://fr.openfoodfacts.org/produit/0121969151630/pizza-vegetarienne'),
(14, 'pizzas', 'Pizza Margherita', 'farine de blé tendre* 35,8% - mozzarella* 22,4% [lait de vache pasteurisé* - sel - coagulant microbien - ferments lactiques (contient lait ) - correcteur d\'acidité : acide citrique] - purée de tomate* 15,2% - eau - tomates semi-séchées* 7,4% - semoule de blé dur* - sel - levure. Traces d\'œuf et soja *Ingrédients issus de l\'agriculture biologique.', 'c', 'Franprix', 'Franprix', 'https://fr.openfoodfacts.org/produit/3263858810819/pizza-margherita-franprix'),
(15, 'pizzas', 'Pizza 4 fromages', '', 'd', '', 'Casa Morando', 'https://fr.openfoodfacts.org/produit/26011639/pizza-4-fromages-casa-morando'),
(16, 'pizzas', 'Pizza poulet mozzarella', '', 'c', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710478781/pizza-poulet-mozzarella-auchan'),
(17, 'pizzas', 'Ristorante Pizza Mozzarella', 'Farine de BLÉ, 21% purée de tomate, 21% MOZZARELLA, 8,3 % tomates cerises, huile de colza, ÉDAM, eau, levure de boulangerie, basilic, sel, sucre, persil, épinards, amidon modifié, ail, jus de citron, poivre, protéines végétales hydrolysées, émulsifiant (mono - et diglycérides d\'acides gras), maltodextrine, poivre de Cayenne, caramel.', 'c', 'Coles,Bilo,Woolworths,Willys,Coop Konsum,Magasins U', 'Dr. Oetker', 'https://fr.openfoodfacts.org/produit/4001724819806/ristorante-pizza-mozzarella-dr-oetker'),
(18, 'pizzas', 'Pizza Saumon Crème + Fromage Maasdam', 'Pâte 53% : farine de blé (contient gluten), eau, huile de tournesol, levure boulangère, sel. Garniture 47% : crème épaisse légère (contient lait) 22,3% (contient épaississants : phosphate de diamidon hydroxypropylé, pectines), saumon fumé (saumon (poisson) (Salmo salar), sel) 13,8%, fromage maasdam râpé (contient lait) 12,5% (contient anti-agglomérant : amidon de pomme de terre), huile de tournesol, sel, épices et plantes aromatiques, sucre, extrait d\'épices et de plantes aromatiques.', 'd', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710454808/pizza-saumon-creme-fromage-maasdam-auchan'),
(19, 'pizzas', 'Pizza royale familiale', '', 'b', '', 'Toupargel', 'https://fr.openfoodfacts.org/produit/4002084335043/pizza-royale-familiale-toupargel'),
(20, 'pizzas', 'Pizza napoli', '', 'c', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710472000/pizza-napoli-auchan'),
(21, 'spread', 'CONFITURE D\'EGLANTINE', '', 'd', '', 'Thorem,Favols', 'https://fr.openfoodfacts.org/produit/3283875623308/confiture-d-eglantine-thorem'),
(22, 'spread', 'Mûres sans pépins', 'mûres sans pépins, sucre, gélifiant: pectine de fruits', 'd', '', 'Eric Bur', 'https://fr.openfoodfacts.org/produit/3144550005751/mures-sans-pepins-eric-bur'),
(23, 'spread', 'Confiture de framboises artisanale NORMANDIE GOURMANDE', 'Framboise et sucre', 'c', '', 'Maitres laitiers en normandie', 'https://fr.openfoodfacts.org/produit/3515580000014/confiture-de-framboises-artisanale-normandie-gourmande-maitres-laitiers-en-normandie'),
(24, 'spread', 'Gelée extra de groseilles', '', 'd', 'Netto', 'Netto', 'https://fr.openfoodfacts.org/produit/3250391376032/gelee-extra-de-groseilles-netto'),
(25, 'spread', 'Peanut Butter Crunchy', '', 'd', '', 'Prozis', 'https://fr.openfoodfacts.org/produit/5600380891530/peanut-butter-crunchy-prozis'),
(26, 'spread', 'Mantiquilla tradicional', '', 'e', '', 'Reny Picot', 'https://fr.openfoodfacts.org/produit/8410379922001/mantiquilla-tradicional-reny-picot'),
(27, 'spread', 'Pindakaas 100%', '', 'd', '', 'AH', 'https://fr.openfoodfacts.org/produit/8718906424920/pindakaas-100-ah'),
(28, 'spread', 'Tahin Tostado', 'Graines de sésame grillées* (100%).', 'd', '', 'NaturGreen', 'https://fr.openfoodfacts.org/produit/8437011502322/tahin-tostado-naturgreen'),
(29, 'spread', 'Confiture extra abricot', 'Abricot Bergeron, sucre, gélifiant : pectine.', 'c', '', 'Alain Milliat', 'https://fr.openfoodfacts.org/produit/3556009998345/confiture-extra-abricot-alain-milliat'),
(30, 'spread', 'Goldessa Original', '', 'd', '', 'Milbona', 'https://fr.openfoodfacts.org/produit/20103286/goldessa-original-milbona'),
(31, 'spread', 'Choko linette (pâte à tartiner sans lait)', 'sucre de canne roux du Brésil 37%, huile de palme non hydrogénée, noisette entière 14.9%, noix de cajou 13.5%, cacao 6%, extrait de vanille', 'e', 'Biocoop', 'Noiseraie,Chocolinette', 'https://fr.openfoodfacts.org/produit/3760076001543/choko-linette-pate-a-tartiner-sans-lait-noiseraie'),
(32, 'spread', 'Rillettes de de Bretagne sardines au sel de Guérande', 'Filets de _sardines_ 60% (pêchées en océan atlantique nord-est) - eau - _crème_ 7,6% - huile de colza - oignon - jus de citron concentré - fibres de canne à sucre - sel de guérande 0,7% - blanc d\'_œuf_ - protéines de _lait_ - épaississants : farine de graines de caroube, carraghénanes - poivre', 'c', 'Casino', 'Casino Ca Vient D\'Ici,Casino', 'https://fr.openfoodfacts.org/produit/3222476288813/rillettes-de-de-bretagne-sardines-au-sel-de-guerande-casino-ca-vient-d-ici'),
(33, 'spread', 'Fleuron de Canard', 'Foie maigre de canard, graisse de canard, _crème_ fraîche, _oeuf_ (ponte au sol),  fibre de chicorée, sel, sucre, poivre, antioxydant : ascorbate de sodium, conservateur : nitrite de sodium, colorant : lutéine.', 'd', 'Auchan,Franprix,Magasins U', 'Fleury Michon', 'https://fr.openfoodfacts.org/produit/3095756220014/fleuron-de-canard-fleury-michon'),
(34, 'spread', 'Préparation De Fruits Fraise De Dordogne', '', 'c', '', 'La Grande Epicerie de Paris', 'https://fr.openfoodfacts.org/produit/3346041395383/preparation-de-fruits-fraise-de-dordogne-la-grande-epicerie-de-paris'),
(35, 'spread', 'Abricot', 'Abricots* 55 %, sucre de canne brut*, gélifiant: pectine, jus de citron concentré* *de l\'agriculture biologique Peut contenir des morceaux de noyaux.', 'c', 'Alnatura', 'Alnatura', 'https://fr.openfoodfacts.org/produit/4104420037427/abricot-alnatura'),
(36, 'spread', 'Pâté de Foie de porc', 'Gras de porc, foie de porc 29 %, eau, oeuf frais, lait frais, farine de blé, sel, oignon, ail, arômes naturels, nitrite de sodium.', 'e', 'Intermarché, Delhaize', 'William Saurin', 'https://fr.openfoodfacts.org/produit/3038356804185/pate-de-foie-de-porc-william-saurin'),
(37, 'spread', 'Rillettes d\'oie', '', 'e', '', '', 'https://fr.openfoodfacts.org/produit/3351090000430/rillettes-d-oie'),
(38, 'spread', 'Myrtille Sauvage cuite au chaudron', 'myrtilles sauvages 45%, sucre, pommes, gélifiant : pectine si nécessaire, jus de citron concentré.', 'c', 'Carrefour, Magasins U', 'Lucien Georgelin', 'https://fr.openfoodfacts.org/produit/3330720251114/myrtille-sauvage-cuite-au-chaudron-lucien-georgelin'),
(39, 'snacks', 'Snack Pois saveur Crème oignon', 'Farine de pois cassés 76%, farine de riz, huile de tournesol, arôme naturel (contient lait), fibre de pomme. traces éventuelles d\'arachides, de crustacés et de gluten.', 'a', '', 'U', 'https://fr.openfoodfacts.org/produit/3256227744167/snack-pois-saveur-creme-oignon-u'),
(40, 'snacks', 'Sablé Nature Graines de Chia', 'Farine intégrale de _blé_, farine de _blé_, sucre de canne roux, huile de colza, graines de chia noires 5,5%, fibre de _blé_, amidon de _blé_; flocons d\'_avoine_ complet, arômes naturels, poudres à lever, (diphosphates, carbonates de sodium), émulsifiant : lécithines de colza, sel marin.', 'c', 'Auchan', 'Gerblé,Nutrition et Santé S.A.S.', 'https://fr.openfoodfacts.org/produit/3175681135864/sable-nature-graines-de-chia-gerble'),
(41, 'snacks', 'Pitch', '', 'd', 'Delhaize', 'Brioches Pasquier', 'https://fr.openfoodfacts.org/produit/3256540000131/pitch-brioches-pasquier'),
(42, 'snacks', 'Les acras de morue sauce piquante', 'Morue 413, (gadus spp.), Œuf entier, farine de blé, pomme de terre, poivrons rouges rissoles à l\'huile de tournesol, ciboule 2,6%, ail. échalotes, huile de colza, arômes (contient poisson, lait, gluten), sel, poudre à lever (diphosphate, carbonate de sodium, amidon de Blé), purée de Piment (eau, piment, fort, sel, huile d\'olive, vinaigre, gingembre, : E202) Cuisson en huile de tournesol Traces éventuelles de crustacés', 'c', '', 'Briau', 'https://fr.openfoodfacts.org/produit/3571492480009/les-acras-de-morue-sauce-piquante-briau'),
(43, 'snacks', 'Brioches parisiennes', 'Farine de BLÉ française 55%, ŒUFS entiers frais 12.5%, sucre, BEURRE pâtissier 8,5%, arômes naturels (contient alcool), sel, levure, poudre de LAIT écrémé, GLUTEN de BLÉ, émulsifiant (E471), épaississant (farine de caroube), colorant (béta carotène).\r\n\r\nTraces éventuelles de fruits à coque.', 'd', '', 'la fournée dorée', 'https://fr.openfoodfacts.org/produit/3587220003587/brioches-parisiennes-la-fournee-doree'),
(44, 'snacks', 'Croustillants cacahuète', 'Semoule de maïs 67%, cacahuètes (_arachide_) grillées moulues 34%, huile de tournesol, sel, arômes naturels, maltodextrine.', 'd', 'Carrefour, Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710307487/croustillants-cacahuete-auchan'),
(45, 'snacks', 'Tuiles salées', 'Pomme de terre déshydratée 49% (dont émulsifiant: mono - et diglycérides d\'acides gras et acidifiant: acide citrique), matière grasse végétale (palme) (dont acidifiant: acide citrique), amidons (blé et pomme de terre), sirop de glucose de blé, sel, émulsifiant : mono - et diglycérides d\'acides gras (huile de colza), sulfites.', 'c', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710322701/tuiles-salees-auchan'),
(46, 'snacks', 'Haribo primvera', '', '', '', 'Haribo', 'https://fr.openfoodfacts.org/produit/4001686405574/haribo-primvera'),
(47, 'snacks', 'Cookies au chocolat', 'chocolat noir* 23% ( cacao en pâte*, sucre de canne brut*, beurre de cacao*, Émulsifiant: lécithine de soja*), amidon de maïs*, sucre de canne brut*, noix de cajou* 7 % , graisse de palme*, huile de tournesol*, farine de millet complet*, Farine de riz complet*, farine de soja* 2%, cacao* maigre en poudre, sirop d\'agave*, épaississant: gomme guar*, sel marin, gousse de vanille Bourbon* moulue, poudre à lever: carbonates d\'ammonium \n* issue de l\'agriculture biologique', 'd', '', 'Alnavit', 'https://fr.openfoodfacts.org/produit/4260546670112/cookies-au-chocolat-alnavit'),
(48, 'snacks', 'Les Palets Aux pépites de chocolat', 'Farine de blé 47%, beurre pâtissier 21% (soit 25% en beurre reconstitué), sucre, pépites de chocolat 15% [sucre, pâte de cacao, beurre de cacao, émulsifiant : lécithines (soja), arôme naturel de vanille], œufs, poudre à lever : diphosphates - carbonates de sodium - carbonates d\'ammonium, jaune d\'œufs, sel, poudre de lait écrémé.\r\nPeut contenir des traces de fruits à coque.', 'e', 'Carrefour', 'Carrefour', 'https://fr.openfoodfacts.org/produit/3560071048563/les-palets-aux-pepites-de-chocolat-carrefour'),
(49, 'snacks', 'Turron Duro', '_amande_ 46%, sucre, miel, pain à cacheter (fécule de pomme de terre, huile de tournesol), _blanc d\'oeuf_', 'd', '', 'La Bruja', 'https://fr.openfoodfacts.org/produit/0638564800165/turron-duro-la-bruja'),
(50, 'snacks', 'Belgian dark chocolate with orange peel', 'Chocolat noir (89,5%) (pâte de cacao, sucre, beurre de cacao, arôme naturel (vanille)), zestes d\'orange confites (10%) (zestes d\'orange, sirop de glucose-fructose, sucre, acidifiant (E330)), arôme (0,4%), émulsifiant (0,1%) (lécithine de soja). Cacao: 70% minimum. Contient de traces de lait. Peut contenir des traces de fruits à coque, de gluten et d\'oeuf.', 'e', '', 'Libeert', 'https://fr.openfoodfacts.org/produit/5411901082586/belgian-dark-chocolate-with-orange-peel-libeert'),
(51, 'snacks', 'Chocolat noir Vietnam 73% la tablette de 80 g', '', 'e', '', 'Libeert', 'https://fr.openfoodfacts.org/produit/5411901082616/chocolat-noir-vietnam-73-la-tablette-de-80-g-libeert'),
(52, 'snacks', 'Treets peanut butter cups mini', '28 % peanuts, sugar, palm fat, cocoa mass, cocoa butter, milk sugar, whole milk powder, dextrose, emulsifier: lecithins; table salt, flavouring. Milk chocolate: cocoa solids: 25 % min, milk solids: 14% min', 'e', '', 'The peanut company', 'https://fr.openfoodfacts.org/produit/4000281334500/treets-peanut-butter-cups-mini-the-peanut-company'),
(53, 'snacks', 'Myrtilles', '', '', '', 'Fruits rouges & Co.', 'https://fr.openfoodfacts.org/produit/8718226441904/myrtilles-fruits-rouges-co'),
(54, 'snacks', 'Huntley & Palmers Crackers Cream', '', '', '', '', 'https://fr.openfoodfacts.org/produit/9400553436119/huntley-palmers-crackers-cream'),
(55, 'snacks', 'Prozis zero snack', 'Protéine de Lait, Chocolat noir (23 %) (Édulcorant (Maltitol), Pâte de cacao, Beurre de Cacao, Émulsifiant (Lécithine de SOJA), Arôme), Sirop d\'Oligofructose , Amandes, Humectant (Sirop de Maltitol, Érythritol), Isomalto-oligosaccharide, Eau, Arômes, Correcteur d\'acidité (Acide Citrique), Conservateur (Benzoate de Sodium), Conservateur (Sorbate de Potassium)', 'a', '', 'Prozis', 'https://fr.openfoodfacts.org/produit/5600380894296/prozis-zero-snack'),
(56, 'snacks', 'Chocolat Noir Mini Tablette, 200g', 'Pâte de cacao - sucre - beurre de cacao - cacao maigre en poudre - émulsifiant: lécithine de tournesol - arôme naturel de vanille. Traces éventuelles de fruits à coque, de gluten et de lait Cacao.\' 72% minimum.', 'd', 'Cora', 'Cora', 'https://fr.openfoodfacts.org/produit/3257980085160/chocolat-noir-mini-tablette-200g-cora'),
(57, 'cheeses', 'Mozzarella di latte di Bufala Casa Azzurra', '_Lait_ pasteurisé de bufflonne, _sérum_ naturel, sel, présure.', 'd', 'Banque alimentaire,Carrefour market,Magasins U', 'Casa Azzurra,Cipf Codipal', 'https://fr.openfoodfacts.org/produit/3760056260014/mozzarella-di-latte-di-bufala-casa-azzurra'),
(58, 'cheeses', 'Delta Feta Cheese 200G', '', 'd', '', '', 'https://fr.openfoodfacts.org/produit/5201037507301/delta-feta-cheese-200g'),
(59, 'cheeses', 'Emmental français', '', 'd', 'Cora', 'Cora', 'https://fr.openfoodfacts.org/produit/3257980891693/emmental-francais-cora'),
(60, 'cheeses', 'Leerdammer Extra fines douces et fondantes', 'lait, sel, ferments lactiques, coagulante microbienne', 'd', 'Magasins U', 'Leerdammer', 'https://fr.openfoodfacts.org/produit/3073781083057/leerdammer-extra-fines-douces-et-fondantes'),
(61, 'cheeses', 'Faisselle', '', 'b', '', 'La bressane', 'https://fr.openfoodfacts.org/produit/3302551152052/faisselle-la-bressane'),
(62, 'cheeses', 'Mieux Vivre Bio coeur a coeur', 'lait pasteurisé biologique, sel, ferments lactiques et d\'affinage, présure.', 'd', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710337187/mieux-vivre-bio-coeur-a-coeur-auchan'),
(63, 'cheeses', 'Brique Au Lait De Brebis 200 G, 1 Pièce', '_lait_ entier, ferments _lactiques_, sel, présure, calcium', 'd', 'Carrefour Market', 'Fromagerie de Jussac', 'https://fr.openfoodfacts.org/produit/3499070422503/brique-au-lait-de-brebis-200-g-1-piece-fromagerie-de-jussac'),
(64, 'cheeses', 'Burger\' Cheddar & Emmental 20 Tranches (17 % MG)', 'Fromages (dont emmental: 7 %, dont cheddar: 7 %), lait écrémé reconstitué, beurre, lactosérum, protéines de lait, sels de fonte (E452, E450), épaississant (E407), arôme, sel, conservateur (E202), colorant (Rocou).', 'd', 'Géant,Leclerc, Magasins U', 'Président', 'https://fr.openfoodfacts.org/produit/3032220061377/burger-cheddar-emmental-20-tranches-17-mg-president'),
(65, 'cheeses', 'Emmental Cœur de Meule', '_Lait_, sel, ferments', 'd', 'Leclerc,Magasins U', 'President', 'https://fr.openfoodfacts.org/produit/3228021170022/emmental-coeur-de-meule-president'),
(66, 'cheeses', 'Caprice des Dieux', '_Lait_ de vache et crème pasteurisés de France, sel, ferments lactiques (lait)', 'd', '', 'Caprice des Dieux,Savencia', 'https://fr.openfoodfacts.org/produit/3161711001971/caprice-des-dieux'),
(67, 'cheeses', 'P\'tit ovale', '', 'd', '', '', 'https://fr.openfoodfacts.org/produit/3272320012866/p-tit-ovale'),
(68, 'cheeses', 'Mozzarella bio 100% lait italien', 'Lait pasteurisé de vache*, coagulant micrc ferments lactiques. \r\n\r\n*Ingrédient issu de l\'agriculture biologique. matière grasse sur produit fini 18%.', 'c', '', 'Casa Azzurra', 'https://fr.openfoodfacts.org/produit/3760056265224/mozzarella-bio-100-lait-italien-casa-azzurra'),
(69, 'cheeses', 'Cancoillotte fabriquée en Franche-Comté', 'Eau, metton lactique (lait écrémé pasteurisé de vache, ferments lactiques), beurre, sels de fonte : phosphates de sodium, sel.', 'c', 'Intermarché', 'Reflets de France', 'https://fr.openfoodfacts.org/produit/3245390032034/cancoillotte-fabriquee-en-franche-comte-reflets-de-france'),
(70, 'cheeses', 'Fol Epi Herzhaft Würzig', '_Lait_ de vache pasteurisé, sel, ferments, colorants: rocou, caramel dans la croûte.', 'd', '', 'Fol Épi,Fromageries Perreault,Savencia', 'https://fr.openfoodfacts.org/produit/3090291386690/fol-epi-herzhaft-wurzig'),
(71, 'cheeses', 'Cantal entre-deux', '', 'd', '', '', 'https://fr.openfoodfacts.org/produit/26035208/cantal-entre-deux'),
(72, 'cheeses', 'Perail', 'fromage de brebis au lait pasteurisé', 'd', '', 'Fromageries du Levezou', 'https://fr.openfoodfacts.org/produit/3177890100039/perail-fromageries-du-levezou'),
(73, 'cheeses', 'Cottage cheese', 'lait écrémé (CH), %6 petit-lait, crème, sel de cuisine, protéines du lait, sucre, épais - sissants: E415 et farine de graines 3% de guar, arôme naturel. ngred magro (CH).', 'b', 'Migros', 'Migros', 'https://fr.openfoodfacts.org/produit/7613404013526/cottage-cheese-migros'),
(74, 'desserts', 'Riz Au Lait 4x115g', '', 'c', 'Cora', 'Cora', 'https://fr.openfoodfacts.org/produit/3257980420558/riz-au-lait-4x115g-cora'),
(75, 'desserts', 'Compottes de pomme', 'Purée de pommes 94%, sucre, antioxydant : acide ascorbique. INFORhuTlONS:', 'a', '', 'Paquito Pocket', 'https://fr.openfoodfacts.org/produit/3250392340308/compottes-de-pomme-paquito-pocket'),
(76, 'desserts', 'Riz au lait nature sur lit de caramel au beurre salé', '', 'c', '', 'Nestlé', 'https://fr.openfoodfacts.org/produit/3023290003060/riz-au-lait-nature-sur-lit-de-caramel-au-beurre-sale-nestle'),
(77, 'desserts', 'Compote De Pommes Sans Sucres Ajoutés', 'Pommes (95%), correcteur d\'acidité: acide citrique, antioxydant acide ascorbique', 'a', 'Delhaize', 'Materne', 'https://fr.openfoodfacts.org/produit/5410046010720/compote-de-pommes-sans-sucres-ajoutes-materne'),
(78, 'desserts', 'Pirulo cool cola', 'eau, sirop glucose, sucre, jus de citron (à base de concentré), stabilisants (E422, E412, E410, E407a), colorant (E150a), arômes naturels, acidifiant (E330)', 'b', '', 'Nestlé', 'https://fr.openfoodfacts.org/produit/7613034557032/pirulo-cool-cola-nestle'),
(79, 'desserts', 'Compote pomme rhubarbe', 'Pommes 42%, rhubarbe 42%, sucre, gélifiant : pectine de fruits, antioxydant : acide ascorbique.', 'a', '', 'Andros', 'https://fr.openfoodfacts.org/produit/3608580765547/compote-pomme-rhubarbe-andros'),
(80, 'desserts', 'Creme Dessert Vanille', '', 'c', '', 'Milbona', 'https://fr.openfoodfacts.org/produit/20301422/creme-dessert-vanille-milbona'),
(81, 'desserts', 'Petit', 'Strawberry: Pasteurized skimmed _milk_ 71,5%, sugar 8,1%, pasteurized _cream_ 6,8%, strawberries 6,1%, water, modified corn starch, _lactic_ ferments, concentrated purple carrot juice, natural aroma, calcium phosphate, corrector Acidity: citric acid, vitamin D.\n\nStrawberry-banana: Pasteurized skimmed _milk_ 71,5%, sugar 8,1%, water, pasteurized _cream_ 6,8%, strawberry puree 3,6%, banana puree 2,6%, tapioca modified starch, _lactic_ ferments, concentrated black carrot juice, natural aromas, calcium phosphate, acidity corrector: citric acid, thickener: carrageenans, vitamin D.', 'b', 'Carrefour', 'Carrefour', 'https://fr.openfoodfacts.org/produit/3560070888856/petit-carrefour'),
(82, 'desserts', 'Glace', '', 'd', '', 'Häagen-Dazs', 'https://fr.openfoodfacts.org/produit/3415587305719/glace-haagen-dazs'),
(83, 'desserts', 'Nature à la Noix de coco', 'base de soja ?eau, fèves de soja sans OGM décortiquées (10,4%)), lait de coco (4,3%) (crème de noix de coco, eau), sucre, citrate tricalcique, cal citrique), stabilisant (pectines), arôme naturel, sel marin de table, antioxygènes (extrait riche en tocophérols, esters d\'acides gras de l\'acide ascorbique), vitamines (B12, D2), ferments de yaourt (S. thermophilus, correcteurs d\'acidité (citrates de sodium, acide 0g 23g Lbulgaricus). 21g hidles! 08 Peut', 'b', 'monoprix', 'Alpro', 'https://fr.openfoodfacts.org/produit/12077122/nature-a-la-noix-de-coco-alpro'),
(84, 'desserts', 'Mon Cake Marbré Cacao', 'Farine de _blé_, Sucre, Huile végétale de colza, _œufs_ entiers, Stabilisant: Sorbítols ,Cacao maigre en poudre 2,6%, Émulsifiant : mono-et diglycérides d\'acides gras (origine végétale) (E471), Sel, Poudres à lever : diphosphates (E450i) et carbonates de sodium (E500i),  Arômes naturels (contient _lait_ , contient alcool &lt; 0,4 %).', 'd', 'Intermarché', 'Ker Cadélac', 'https://fr.openfoodfacts.org/produit/3259420535013/mon-cake-marbre-cacao-ker-cadelac'),
(85, 'desserts', 'Macadamia nut brittle', 'crème fraîche (35%), lait écrémé concentré, sucre, jaune d\'œuf, sirop de glucose, noix de macadamia, huile de noix de coco, beurre, poudre à lever : bicarbonate de sodium; sel, arôme naturel de vanille', 'd', 'Delhaize', 'Häagen-Dazs', 'https://fr.openfoodfacts.org/produit/3415581122015/macadamia-nut-brittle-haagen-dazs'),
(86, 'desserts', 'Le moelleux aux noix', 'Sucre roux de canne 31%, blancs d\'_œufs_, _beurre_, farine de _blé_, _noix_ 10% (poudre et éclats de _noix_), stabilisant : sorbitols, _œufs_ entiers, sel, poudres à lever (diphosphates et carbonates de sodium), amidon de _blé_, antioxydant : acide ascorbique.', 'e', 'Magasins U', 'Les Comtes de la Marche', 'https://fr.openfoodfacts.org/produit/3760026383033/le-moelleux-aux-noix-les-comtes-de-la-marche'),
(87, 'desserts', 'Eclipse', '', 'd', '', 'Gelatelli', 'https://fr.openfoodfacts.org/produit/20350666/eclipse-gelatelli'),
(88, 'desserts', 'Blondie', 'Sucre, farine de _blé_ (_gluten_), beurre 16% (_lait_), chocolat au _lait_ 16% (sucre, beurre de cacao, _lait_ entier en poudre, pâte de cacao, _lait_ écrémé en poudre, émulsifiant : lécithine de _soja_, arôme naturel de vanille), _œuf_ entier liquide de poule élevée en plein air, _noix de pécan_ 8,9%, caramel 1,7% (sucre, eau, sirop de glucose-fructose de blé et/ou maïs), extrait de vanille Bourbon.', 'e', 'Picard', 'Picard', 'https://fr.openfoodfacts.org/produit/3270160821167/blondie-picard'),
(89, 'desserts', 'Mont Blanc multivariétés', 'Lait (81%), sucre, maltodextrine, cacao maigre en poudre, amidon, amidon transformé, sirop de glucose, praline (sucre, _noisettes_, _amandes_), arôme naturel de vanille de Madagascar, chocolat (poudre de cacao, cacao maigre en poudre, pâte de cacao, sucre), alginate de sodium, carraghénanes, sel, riboflavine amidon transformé, gomme guar, _lait_', 'c', 'Carrefour,Magasins U', 'Mont Blanc', 'https://fr.openfoodfacts.org/produit/3700279302627/mont-blanc-multivarietes'),
(90, 'pizzas', 'Pizza Royale Four à Pierre 370 g', 'Garniture (58,6%): edam). eau, jambon cuit 110%) * (viande de porc (UE), eau, gélatine de porc, et triphosphates, sel, sirop de glucose, gélifiant: E407a. arôme, arôme de fumée, antioxydant: erytb6rbale de sodium, conservateur I nitrite de sodium], purée de tomates. sauce façon pesto (eau, huile de tournesol, crème en poudre,basiüc, pulpe d\'ail, persil, amidon de A pomme de terre). olives noires (3%)•. amidon modifié de pomme de terre, pulpe d\'ail, sel, persil, origanv poudre de betterave, extra\'lt de pmvre. Pâte cuite 141,4%1: farine de blé, eau. levure boulangère, huile de tournesol, levain de seigle et de ble (soja), sel, sucre, extrait de maltdorge. • % exprimés par rapport au produit fini. Peut contenir : poisson.', 'c', '', 'Buitoni', 'https://fr.openfoodfacts.org/produit/7613036011723/pizza-royale-four-a-pierre-370-g-buitoni'),
(91, 'spread', 'Boursin Ail & Fines Herbes', '_lait_ et _crème_ pasteurisé (origine France), ferments _lactiques_, ail et fines herbes 2,3%, sel, poivre', 'd', 'Magasins U', 'Boursin,Fromagerie BEL', 'https://fr.openfoodfacts.org/produit/3073781099621/boursin-ail-fines-herbes'),
(92, 'spread', 'Beurre DOUX', 'Beurre (crème de lait pasteurisée, ferments lactiques)', '', 'Carrefour', 'Carrefour', 'https://fr.openfoodfacts.org/produit/3560071206604/beurre-doux-carrefour'),
(93, 'spread', 'Crème d\'artichaut Rustique A Paesana', 'Artichauts (80%), Huile d\'olive vierge extra !6%), Ail, sel, Citron, Poivre, onditionné sous vide d\'air, tenir au frais', 'c', '', 'A paesana', 'https://fr.openfoodfacts.org/produit/3512680000098/creme-d-artichaut-rustique-a-paesana'),
(94, 'spread', 'Beurre de choix', '', 'd', 'Migros', 'Valflora', 'https://fr.openfoodfacts.org/produit/7617027159111/beurre-de-choix-valflora'),
(95, 'spread', 'Confiture bonne maman Mon jardin secret', 'Fruits (fraises 39%, framboises 21%), sucre, jus de citrons concentré, gélifiant : pectines de fruits, infusion de fleur de sureau', 'c', '', 'Bonne Maman', 'https://fr.openfoodfacts.org/produit/3608580931171/confiture-bonne-maman-mon-jardin-secret'),
(96, 'spread', 'Confitures Bio Fraises Extra', 'fraises*, sucre de canne*, gélifiants : pectines', 'c', '', 'Coteaux nantais', 'https://fr.openfoodfacts.org/produit/3301595001081/confitures-bio-fraises-extra-coteaux-nantais'),
(97, 'snacks', 'Goûters Fourrés Chocolat', 'Farine de _blé_ (56%), sucre, graisses végétales (palme, palmiste), sirop de glucose, cacao maigre en poudre (1,6 %), poudres à lever (carbonates d\'ammonium, carbonates de sodium, phosphates de calcium), sel, arômes, poudre de _lait_ écrémé, protéines de _lait_, amidon de _blé_, _lactose_ (dont _lait_), farine de _seigle_.', 'e', 'Netto', 'Netto', 'https://fr.openfoodfacts.org/produit/3250391009442/gouters-fourres-chocolat-netto'),
(98, 'snacks', 'Chocoladises Au Lait', '', 'e', '', 'Biscuiterie de l abbaye', 'https://fr.openfoodfacts.org/produit/3226219000823/chocoladises-au-lait-biscuiterie-de-l-abbaye'),
(99, 'snacks', 'Sucette goût Fraise - Citron Vert', 'sucre, sirop de glucose, acidifiants (acide lactique, acide citrique, acide malique), correcteurs d\'acidité (carbonate acide de sodium, citrates de sodium), arômes, concentré-couleur de spiruline, colorants (rouge de betterave, curcumine).', 'd', 'Magasins U', 'Chupa Chups', 'https://fr.openfoodfacts.org/produit/6921211113454/sucette-gout-fraise-citron-vert-chupa-chups'),
(100, 'snacks', 'sablés', 'Farine de blé, Beurre demi-sel (lait), sucre de canne blond, œuf, chocolat noir 4,2 % (pâte de cacao, sucre, beurre de cacao, émulsifiant : lécithine de soja), levure chimique (amidon de maïs, bicarbonate de sodium, diphosphate disodique), sucre vanillé (sucre, amidon, extrait de vanille), sel.', 'e', '', 'Toqué du biscuit', 'https://fr.openfoodfacts.org/produit/3029687002012/sables-toque-du-biscuit'),
(101, 'snacks', 'Sablés pur beurre', 'Farine de _blé_, sucre, _beurre_ concentré, _œufs_ entiers, sel, caramel, poudre à lever : diphosphate disodique, carbonate acide de sodium.', 'e', '', 'La Trinitaine', 'https://fr.openfoodfacts.org/produit/3260260031443/sables-pur-beurre-la-trinitaine'),
(102, 'snacks', 'Surffizz', 'Sucre, Sirop de glucose-fructose, Amidon modifié, Gélatine, Acidifiants (Acide lactique, Acide citrique, Acide malique), Correcteur d\'acidité (Malates de sodium), Arômes, Denrées alimentaires colorantes (Concentré de Radis, Carthame, Patate douce, Pomme, Cerise, Cassis), Colorants (E161b, E100 E133)', 'd', '', 'Lutti', 'https://fr.openfoodfacts.org/produit/3116740032427/surffizz-lutti'),
(103, 'snacks', 'Barre repas chocolat', 'Isolat de protéines de soja (39 0%), fructose, inuline, fibres d\'avoine, huile de soja, arômes, mélange de minéraux (citrate de calcium, oxyde de magnésium, fumarate ferreux, sélénite de sodium, oxyde de zinc, carbonate de manganèse, chlorure de chrome (III), iodure de potassium, citrate de cuivre), phosphate de potassium, émulsifiant (lécithine de soja), épaississants (gomme xanthane, carraghénane, gomme guar, pectine), colorant (rouge de betterave), mélange de vitamines (acide L-ascorbique, acétate de DL-alpha-tocophéryle, bêta-carotène, nicotinamide, D-pantothénate de calcium, D-biotine, cholécalciférol, chlorhydrate de pyridoxine, chlorhydrate de thiamine, cyanocobalamine, acide ptéroylmonoglutamique, riboflavine), chlorure de sodium, antiagglomérant (dioxyde de silicium), papaye en poudre (0,02 %), persil en poudre (0,02 %), jus de myrtille en poudre (0,02 0%), jus de grenade en poudre (0,02 0%). Conseil : pour les allergènes, y compris les céréales contenant du gluten, voir les ingrédients en gras.', 'd', 'https://supplements-online.ecwid.com/Instructions-for-discounts-on-herbalife-products-p157540163', 'Herbalife', 'https://fr.openfoodfacts.org/produit/2767629023305/barre-repas-chocolat-herbalife'),
(104, 'snacks', 'Macaron', 'sucre, noix de coco 24%, blancs d\'œufs, farine de riz, fécule de pomme de terre, lait écrémé en poudre, protéines de lait. Peut contenir du soja, du sulfite et des traces de fruits à coque.', 'e', '', 'La trinitaine', 'https://fr.openfoodfacts.org/produit/3260260200054/macaron-la-trinitaine'),
(105, 'snacks', 'Sticks cannelle', 'Farine de _blé_ - sucre - _beurre_ 27,5 % - levure - cannelle 0,8 % - sel.', 'e', 'Franprix', 'Franprix', 'https://fr.openfoodfacts.org/produit/3263850597497/sticks-cannelle-franprix'),
(106, 'snacks', 'Croibleu', 'Sirop de glucose*, sucre de canne&quot;, extrait de romarin huile essentielle de menthe*, menthol*.* issus de lagriculture biologique. Peut contenir des traces de lait et de fruits à coque. L\'ingrédient primaire (sirop de glucose) ne provient pas exclusivement de France.', 'd', '', 'Croibleu', 'https://fr.openfoodfacts.org/produit/3501275130296/croibleu'),
(107, 'snacks', 'Succès aux noix', 'Mousse aux noix et amandes 59,5 %: _lait_ écrémé réhydraté, sucre liquide, _beurre_ concentré, pâte de noix 11 % (_noix_ 85 %, sucre), _amande_ en poudre 10 %, eau, jaune d\'_œuf_ liquide pasteurisé sucré, _lactose_ et protéines de _lait_, amidon de riz, gélatine de porc, kirsch gélifié (kirsch, épaississant: gomme xanthane), arôme naturel de vanille, antioxydant: acide ascorbique.\r\n\r\nMacarons aux amandes 38,8 %: sucre, amandes en poudre 20 %, sucre glace (sucre, anti-mottant: fécule de pomme de terre), blanc d\'œuf liquide pasteurisé (blanc d\'_œuf_, épaississants: gomme de guar, gomme xanthane), eau, fécule de pomme de terre, blanc d\'_œuf_ en poudre, épaississant: gomme xanthane.\r\n\r\nDécor 1,7 %: _amandes_ effilées. 1,7+', 'c', 'Picard', 'Picard', 'https://fr.openfoodfacts.org/produit/3270160369096/succes-aux-noix-picard'),
(108, 'snacks', 'Tubo 150 Sucettes Acidule Chupa Chups', 'Ingrédients (pour sucettes goûts fraise, cerise, orange et pomme): sucre, sirop de glucose, purée de fruits (3%) (pomme, cerise, framboise, ananas, citron vert, citron, fraise, pêche, banane, orange, myrtille, mûre, mangue, pastèque, kiwi), acidifiants (acide lactique, acide malique, acide citrique), arômes, colorants (E100, E162).  Ingrédients (pour sucettes goût cola): sucre, sirop de glucose, acidifiants (acide lactique, acide malique, acide citrique), arômes, colorant (E150d). Ingrédients (pour sucettes goûts lait-fraise et framboise-vanille): sucre, sirop de glucose, _lactosérum_ en poudre, purée de fruits (pomme, cerise, framboise, ananas, citron vert, citron, fraise, pêche, banane, orange, myrtille, mûre, mangue, pastèque, kiwi) (3%), _lait_ entier en poudre (1,6%), acidifiants (acide lactique, acide malique, acide citrique), beurre de cacao, arômes, colorants (E100, E162, E163).', 'd', '', 'Chupa chups', 'https://fr.openfoodfacts.org/produit/8410031991314/tubo-150-sucettes-acidule-chupa-chups'),
(109, 'snacks', 'Gianduja nougatine', 'sucre, beurre de cacao, poudre de lait, lactose, noisettes, pâte de cacao, nougatine de noisettes (noisettes, sucre) 5%, poudre de lait écrémé, émulsifiant (lécithine de soja), extrait de malt d\'orge, arôme. Peut contenir du blé et d\'autres fruits à à coque.', 'e', '', 'Lindt', 'https://fr.openfoodfacts.org/produit/3046920046459/gianduja-nougatine-lindt'),
(110, 'snacks', 'Epicerie / Epicerie Sucrée / Chocolat', 'patg_dg cacao*, sucre de canne blond*, beurre de cacao*, émulsifiant : lécithine de tournesol, extrait de vanille*, *Ingrédients agricoles issus de l\'agriculture biologique. Ingrédients d\'ori ine a ricole issus du commerce é uitable filières cacao et vanille 55% du total des in rédients contrôlés ar ECOCERT ENVIRONNEMENT selon le référentiel ESR dis oniblesurwww.ecocert.com.', 'e', '', 'Kaoka', 'https://fr.openfoodfacts.org/produit/3477730008069/epicerie-epicerie-sucree-chocolat-kaoka'),
(111, 'snacks', '4 éclairs au chocolat', '', 'e', '', '', 'https://fr.openfoodfacts.org/produit/3257982267977/4-eclairs-au-chocolat'),
(112, 'snacks', 'Palets bretons', 'Farine de _blé_, sucre, _beurre_ pâtissier 25%, _œufs_, poudres à lever : diphosphates - carbonates de sodium, sel, émulsifiant : lécithines de _soja_, colorant : caroténoïdes.', 'e', 'Super U,Magasins U', 'U', 'https://fr.openfoodfacts.org/produit/3256220211222/palets-bretons-u'),
(113, 'snacks', 'Les frit\'pettes d\'Alice', 'Pommes de terre, huile de tournesol, sel', 'e', '', 'SAS SDRE', 'https://fr.openfoodfacts.org/produit/3325410000295/les-frit-pettes-d-alice-sas-sdre'),
(114, 'cheeses', 'Parmigiano Reggiano Dop Shaved Zakje 100 Gram (italiamo)', 'lait cru de vache, sel, présure. Mat. Gr. dans le k\'dal Mipaaì??? osphère protectrice.', 'd', 'Lidl', 'italiamo', 'https://fr.openfoodfacts.org/produit/20516901/parmigiano-reggiano-dop-shaved-zakje-100-gram-italiamo'),
(115, 'cheeses', 'Emmental râpé fondant', '_Lait_ pasteurisé de vache, sel, ferments _lactiques_, enzyme coagulante', '', 'carrefour', 'Carrefour', 'https://fr.openfoodfacts.org/produit/3270190207689/emmental-rape-fondant-carrefour'),
(116, 'cheeses', 'Camembert', 'lait (origine France), ferments lactiques et d\'affinage, sel.', 'd', 'Magasins U', 'President', 'https://fr.openfoodfacts.org/produit/3228021170039/camembert-president'),
(117, 'cheeses', 'Emmental français râpé', '', 'd', '', '', 'https://fr.openfoodfacts.org/produit/3701002400771/emmental-francais-rape'),
(118, 'cheeses', 'Rondou', '_lait_ (origine : France), sel, ferments lactiques (contient _lait_), enzyme coagulante microbienne.', 'd', 'Leader Price', 'Leader Price', 'https://fr.openfoodfacts.org/produit/3263859360115/rondou-leader-price'),
(119, 'cheeses', 'Emmental râpé', 'Lait de vache pasteurisé, sel, ferments (dont lait). [LI facultatif]', 'd', 'Leclerc', 'Les Croisés,Marque Repère,Scamark (Filiale E. Leclerc)', 'https://fr.openfoodfacts.org/produit/3564700014646/emmental-rape-les-croises'),
(120, 'cheeses', 'Petit Brie', '', 'd', '', 'Laita', 'https://fr.openfoodfacts.org/produit/3412290055696/petit-brie-laita'),
(121, 'cheeses', 'Pointe De Brie 200G', '_Lait_ de vache pasteurisé, sel, ferments.', 'd', '', 'Belle France', 'https://fr.openfoodfacts.org/produit/3258561429069/pointe-de-brie-200g-belle-france'),
(122, 'cheeses', 'Parmigiano reggiano', 'Lait, sel, présure. 32% minimun de matière grasse extrait sec 28% minimum de matière grasse/produit fini.', 'd', '', 'Casale', 'https://fr.openfoodfacts.org/produit/26022406/parmigiano-reggiano-casale'),
(123, 'cheeses', 'Tomme à la crème', 'Fromage suisse à pâte molle, à la crème, au lait pasteurise', 'd', '', 'Jean-Louis', 'https://fr.openfoodfacts.org/produit/7610433434339/tomme-a-la-creme-jean-louis'),
(124, 'cheeses', 'La Faisselle', '_Lait_ pasteurisé.', 'b', 'Dia,Magasins U,carrefour', 'Rians', 'https://fr.openfoodfacts.org/produit/3184670001141/la-faisselle-rians'),
(125, 'cheeses', 'La Faisselle et son coulis de Framboises', '2 FROMAGES FRAIS EN FAISSELLE au lait de vache (Origine : France) et à la crème (Origine : France) pasteurisés et leur coulis. [Coulis de framboise: purée de framboise (75%), sucre.]', 'b', 'Magasins U,Delhaize', 'Rians', 'https://fr.openfoodfacts.org/produit/3184670001882/la-faisselle-et-son-coulis-de-framboises-rians'),
(126, 'cheeses', 'Tomme de brebis', '', 'd', '', '', 'https://fr.openfoodfacts.org/produit/3364860000011/tomme-de-brebis'),
(127, 'desserts', 'Dessert de Fruits Pomme', 'Fraises 50%, pommes 25%, sucres extraits de fruits, gélifiant : pectines.', 'b', '', 'Bergams', 'https://fr.openfoodfacts.org/produit/3330720311924/dessert-de-fruits-pomme-bergams'),
(128, 'desserts', 'Pot crème glacée Caramel au Beurre salé', 'z ErŒB#éesentélaboréesà base d\'ingrédients naturels (crème arôme artificiel. Pour plus d\'onctuosité, retirez votre crème glacée au aramel avec sauce aramel salé (1096) et éda6 (31%), sucre, lait écrémé concentré, jaune d\'œuf, sim de huile de noix de coco, sel, émulsifiant : lécithine de rz*tùlesingrédents en gras. Peut contenir des traces dtingrdtenùib,ui\'t : ne pas recongeler. Conservation à - 18 r. À conscer de', 'e', '', 'Haagen-Dazs', 'https://fr.openfoodfacts.org/produit/3415580502511/pot-creme-glacee-caramel-au-beurre-sale-haagen-dazs'),
(129, 'desserts', 'Danette Pop Chocolat Billes 3 Chocos', 'Crème dessert au chocolat : \r\nlait demi-écrémé (72,3%), sucre, crème (lait), chocolat (2,0%) (sucre, pâte de cacao, cacao maigre, émulsifiant (lécithine de soja), arôme), cacao maigre, épaississants (amidon transformé, carraghénanes), perméat de petit lait (lactosérum) en poudre, amidon. Lait: Origine France\r\n\r\nBilles soufflées enrobées de 3 chocolats (6,8%) :\r\nbilles soufflées 2,7% (farine de blé, sucre, malt de blé, poudre à lever (carbonate de sodium), huile de tournesol, sel, dextrose), chocolat noir 1,4% (sucre, pâte de cacao, beurre de cacao, émulsifiant (lécithine de soja), arôme), chocolat blanc 1,4% (sucre, beurre de cacao, poudre de lait entier, poudre de lactosérum (lait),émulsifiant (lécithine de soja), arôme), chocolat au lait 1,3% (Sucre, beurre de cacao, poudre de lait entier, pâte de cacao, émulsifiant (lécithine de soja), arôme), agent d\'enrobage (gomme arabique). Peut contenir : Fruits à coques, autres céréales contenant du gluten.', 'c', 'Cora,Magasins U,Delhaize,Intermarché', 'Danone', 'https://fr.openfoodfacts.org/produit/3033491012020/danette-pop-chocolat-billes-3-chocos-danone'),
(130, 'desserts', 'La creme brulée  au Rhum', 'CRÉME 96g : Crème (57%), lait\' écrémé, œufs\' entiers frais (11%), sucre, rhum de Guadeloupe (3%), jaune d\'œufs frais. GARNITURE 4g : éclats de (sirop de glucose, sucre).  Nos ne sont pas issus de poules en cage.', 'd', 'Magasins U', 'Rians', 'https://fr.openfoodfacts.org/produit/3184670008089/la-creme-brulee-au-rhum-rians'),
(131, 'desserts', 'Protein Pudding Choco Mountain', 'latt (1,4% de graisses, pasteu? risé), 8,1% concentré de protéine lactique, I cacao, stabilisants.\' carraghénanes, car/ boxyméthyl cellulose sodique; édulcorants: acésulfame?K sucralose; arôme, lactase. 1 de glucides en moins par rapport à un produit similaire. 2 contient des sucres naturellement pré - sents', 'a', 'Migros', 'Chiefs', 'https://fr.openfoodfacts.org/produit/7640151710743/protein-pudding-choco-mountain-chiefs'),
(132, 'desserts', 'Dessert de fruits pomme poire x4', 'Purée de pommes 65 %, purée de poires 28 %, sucre, antioxydant : acide ascorbique, acidifiant : acide citrique.', 'a', 'Leclerc', 'Marque Repère,Douceur du verger', 'https://fr.openfoodfacts.org/produit/3564700198278/dessert-de-fruits-pomme-poire-x4-marque-repere'),
(133, 'spread', 'Le petit crémeux', 'Fromage (lait pasteurisé, proteines de lait, chlorure de calcium,  culture bactérienne, enzyme microbienne, colorant naturel ),  eau, beurre, poudre de lactosérum, maltodextrine, sel, polyphosphate de sodium, phosphate trisomique, citrate de sodium, sorbate de potassium, colorant naturel, acide citrique, \r\nCONTIENT : Lait,', 'd', 'Pasquier', 'La fromagerie Boivin', 'https://fr.openfoodfacts.org/produit/0621879007503/le-petit-cremeux-la-fromagerie-boivin'),
(134, 'snacks', 'Tortilla chips', '', 'd', 'Alcanpo', 'Santa Maria', 'https://fr.openfoodfacts.org/produit/7311310032074/tortilla-chips-santa-maria'),
(135, 'snacks', 'Barre en cas', 'Concentré de protéines de lait (protéines de lactosérum, caséinate de calcium (contient du lait)), sirop de glucose, sirop de fructose, enrobage au chocolat au lait (1 7 %) (sucre, poudre de lait, beurre de cacao, pâte de cacao, émulsifiant (lécithine de soja), arôme), pâte d\'amande (6,5 %), gélatine, riz soufflé, arômes. Conseil : pour les allergènes, voir les ingrédients en gras. PEUT CONTENIR DES TRACES D\'ARACHIDE ET DE GLUTEN.', 'd', 'https://supplements-online.ecwid.com/Instructions-for-discounts-on-herbalife-products-p157540163', 'Herbalife', 'https://fr.openfoodfacts.org/produit/8017759646320/barre-en-cas-herbalife'),
(136, 'snacks', 'Barre repas équilibre', 'Granulés de _soja_, sirop de fructose-glucose, flocons de _soja_ (isolat de protéines de _soja_, amidon de tapioca, sel), nappage au yaourt 8,9 % [sucre, beurre de cacao, poudre de yaourt écrémé (_lait_) (1 0 %), lactose (_lait_), émulsifiant (lécithine de _soja_), arôme, acidifiant (acide citrique)], polydextrose, sirop de glucose, sirop d\'oligofructose, concentré de protéines de soja, pépites à base de fruits 3,6 % [sirop de fructose-glucose, sirop de glucose, humectant (glycérol), sucre, fibre de _blé_, concentré de fruits mélangés 22 % {purée concentrée de myrtille (10 %), purée concentrée d\'açaï (8 %), jus concentré de grenade (4 %) }, gélifiant (pectine), graisse de palme, correcteurs d\'acidité (acide malique, acide citrique), arôme], isolat de protéines de _soja_, flocons de maïs extrudés, (farine de maïs, farine de _blé_, sucre, malt de _blé_, sel), fructose, huile de tournesol, gomme d\'acacia, phosphate dipotassique, phosphate tricalcique, arômes, sel, correcteur d\'acidité (acide citrique), pré-mélange de vitamines et minéraux (diphosphate ferrique, acide L-ascorbique, nicotinamide, oxyde de zinc, acétate de DL-alpha - tocophéryle, sulfate de cuivre, D-pantothénate de calcium, sulfate de manganèse, riboflavine, chlorhydrate de pyridoxine, chlorhydrate de thiamine, acétate de rétinol, acide ptéroylmonoglutamique, D-biotine, iodure de potassium, sélénite de sodium, cholécalciférol, cyanocobalamine), émulsifiant (lécithine de _soja_), oxyde de magnésium. Conseil : pour les allergènes, y compris les céréales contenant du gluten, voir les ingrédients en gras.', '', 'https://supplements-online.ecwid.com/Instructions-for-discounts-on-herbalife-products-p157540163', 'Herbalife', 'https://fr.openfoodfacts.org/produit/4015600558994/barre-repas-equilibre-herbalife'),
(137, 'snacks', 'Bâtonnets torsadés chocolat au lait', 'Chocolat au lait 49 % (sucre ; beurre de cacao ; pâte de cacao ; poudre de lait écrémé ; lactose ; beurre concentré ; émulsifiants : lécithines (soja), E476 ; arôme naturel de vanille), farine de blé, sucre, graisse de palme, lactose et protéines de lait, amidon de riz, sel, levure désactivée, poudre à lever : E503, correcteur d\'acidité : E524. \nTraces de fruits à coque et œufs.', 'e', 'Leclerc', 'P\'tit Déli,Marque Repère', 'https://fr.openfoodfacts.org/produit/3564700753972/batonnets-torsades-chocolat-au-lait-p-tit-deli'),
(138, 'snacks', 'Patatas Fritas Caseras Frit Ravich 270G', '', 'c', '', 'Frit ravich', 'https://fr.openfoodfacts.org/produit/8410564032317/patatas-fritas-caseras-frit-ravich-270g'),
(139, 'snacks', 'Cookies', '', 'e', 'Dia', 'Dia', 'https://fr.openfoodfacts.org/produit/8480017169297/cookies-dia'),
(140, 'snacks', 'Patatas onduladas', '', 'c', '', 'Snack Day', 'https://fr.openfoodfacts.org/produit/20330118/patatas-onduladas-snack-day'),
(141, 'cheeses', 'Burrata biologique', 'Lait de vache biologique, crème biologique, sel, présure. Sans conservateurajce Allergène: Lait. 45% do matière grasse/sèche. À conserver entre OOC et +40C.', 'c', '', 'Bioetika', 'https://fr.openfoodfacts.org/produit/3760019721088/burrata-biologique-bioetika'),
(142, 'snacks', 'Saveur Barbecue', 'Pommes de terre 61%, huiles végétales (tournesol, colza, en proportion variable), base aromatisante barbecue [sucre, arôme (dont soja), chapelure (de blé), exhausteur de goût (glutamate de sodium), paprika, poudre d\'oignon, poudre de tomate, poudre d\'ail, correcteurs d\'acidité (acide citrique, acide malique), colorant (extrait de paprika), arômes de fumée], sel,', 'c', 'Cora,Super U,Magasins U', 'Lay\'s', 'https://fr.openfoodfacts.org/produit/3168930007432/saveur-barbecue-lay-s');
INSERT INTO `products` (`id`, `category`, `product_name`, `ingredients_text`, `nutrition_grade`, `stores`, `brands`, `link`) VALUES
(143, 'snacks', 'Wasabi Mix', 'farine de blé, 19 % cacahuète, 15 % riz, sucre, amidon de maïs modifié, huile palme, sirop de maïs, amidon (pomme de terre, tapioca), sel, sésame, maltodextrine, lactose, sauce soja (eau, soja, bl?, sel), 0,4 % assaisonnement wasabi [sucre, sel, maltodextrine, sauce soja en poudre (soja, blé, sel, maltodextrine), arôme, extrait de levure, huile de tournesol], agent de crémage [sirop de tapioca, huile palme hydrogénée, caséinate de sodium (contient des protéines de laif), stabilisant (E340), émulsifiant (E472e)], arômes (contient des protéines de lait, de la moutarde), algues, oignons en poudre, 0,1 % wasabi en poudre [raifort, wasabi, stabilisant (gomme arabique), amidon de pomme de terre modifié, maltodextrine], extrait de levure, colorant (caramel, extrait de paprika, E100, E141, E150c).', 'd', '', 'Mitsuba', 'https://fr.openfoodfacts.org/produit/8711299041507/wasabi-mix-mitsuba'),
(144, 'snacks', 'Galletas digestive con avena azúcares añadidos', '', 'a', '', 'Santiveri', 'https://fr.openfoodfacts.org/produit/8412170027107/galletas-digestive-con-avena-azucares-anadidos-santiveri'),
(145, 'desserts', 'Moka', 'Crème fraîche, lait entier, sucre, eau, œufs entiers frais, jaune d\'œufs frais, farine de blé, arômes naturels de café, beurre, amidons, caramel, gélifiant : pectine, poudre à lever (diphosphates et carbonates de sodium, farine de blé).', 'd', '', 'Bonne Maman', 'https://fr.openfoodfacts.org/produit/3608580896814/moka-bonne-maman'),
(146, 'spread', 'Crème De Marrons', 'sugar/ chestnuts, water, vanilla extracte 389 of chestnut for 100g of finished product, Total sugar 100g of finished producte Use on bread/ yoguft, cottage bagels or to prepare desserts, After opening keep 10 days Best before : look on tin, Roger cours, une tradition familiale de père en fi!s 1 a family tradition handed down', 'd', '', 'Rager Descours', 'https://fr.openfoodfacts.org/produit/3558370000702/creme-de-marrons-rager-descours'),
(147, 'spread', 'Rillettes de Saint Jacques', '', 'c', '', 'Conserverie des Saveurs', 'https://fr.openfoodfacts.org/produit/3389090017585/rillettes-de-saint-jacques-conserverie-des-saveurs'),
(148, 'snacks', 'Sweet & salted popcorn', 'Maize, Sugar, Sunflower Oil, Salt.', 'd', '', 'Coop', 'https://fr.openfoodfacts.org/produit/5000128975889/sweet-salted-popcorn-coop'),
(149, 'snacks', 'PITCH CHOCO BARRE LAIT', 'Farine de _BLÉ_ 29 % - chocolat au lait 28% sucre, _LAIT_ entier en poudre, beurre de cacao, LACTOSERUM en poudre (_LAIT_), masse de cacao, émulsifiant : lécithine de _SOJA_, arôme naturel de vanille] - Sucre - Levain 9% (farine de _BLÉ_ 5 %, eau, sel) - Eau - Huile de colza - Levure - _ŒUFS_ en poudre (_ŒUFS_ d\'élevage au sol) - BEERRE concentré (_LAIT_) - Fibres de psyllium - émulsifiant: mono et diglycérides d\'acides gras Sel de cuisine _GLUTEN_ de _BLÉ_ - épaississant : farine de graines de caroube, Antioxydant : acide ascorbique - Protéines de _LAIT_.', 'e', '', 'Brioche Pasquier', 'https://fr.openfoodfacts.org/produit/3256540002029/pitch-choco-barre-lait-brioche-pasquier'),
(150, 'snacks', 'Fisherman\'s Friend Pastilles Eucalyptus Menthol Sans Sucres ()', 'Édulcorants: sorbitols. Arômes: extrait de réglisse, menthol, huile d\'eucalyptus, teinture de capsicum. Antiagglomérant: stéarate de magnésium.', 'c', '', 'Fisherman\'s Friend', 'https://fr.openfoodfacts.org/produit/50357215/fisherman-s-friend-pastilles-eucalyptus-menthol-sans-sucres'),
(151, 'snacks', 'Gaufrettes apéritives Maroilles gratiné', 'Maroilles AOP (_lait_) 41%, farine de _blé_, sirop de glucose, _beurre_ pâtissier 13%, poudre de _lait_ entier, _œufs_ entiers, sel, fibre de _blé_, arôme naturel.', 'e', 'Magasins U', 'Tresors Gourmands', 'https://fr.openfoodfacts.org/produit/3700254081684/gaufrettes-aperitives-maroilles-gratine-tresors-gourmands'),
(152, 'snacks', 'Cookie me mix selection', 'Farine de blé, sucre, pepites de chocolat (13,8%): (sucre, pâte de cacao, beurre de cacao, dextrose et émulsifiant lécithine de soja), graisse végétale de palme, pépites de chocolat noir (10%): palle de cacao, sucre, dextrose, cacao en poudre, beurre de cacao, émulsimant: lécithine de soja etarôme), huile de toumesol oléique, morceaux de fruits (2%): (sirop de fructose au glucose, fruit concentré de purée de pomme et jus ?\'orange concentré à 5%, sirop de glucose, humectant glycérol, sucre, fibre de ble, gélifiant pectine, correcteur d\'acidité: acide citrique, arôme naturel et colorant curcumine), lait écrémé en poudre, sirop de glucose et fructose, amidon de blé, poudre à lever: bicarbonate d\'ammonium et bicarbonate de sodium, cacao dégraissé en poudre 0,2%, sel, émulsifiant lécithine de soja, sérum du lait en poudre et arôme. Peut contenir des traces de sésame et de fruits à coque. Conservez bien fermé dans un endroit frais et sec. Préservez du soleil.', 'e', '', 'Florbu', 'https://fr.openfoodfacts.org/produit/8411414013760/cookie-me-mix-selection-florbu'),
(153, 'snacks', 'Cookie cacao pépites', 'Farine de _blé_, édulcorant: maltitol,huile de colza, pépites de chocolat au malitol 11% (édulcorant: maltitol, pâte de cacao, émulsifiant: lécithine de _soja_, cacao maigre en poudre, arôme naturel de vanille), fibre de _blé_, cacao maigre en poudre 4%, son d\'_avoine_, sel marin, émulsifiant: lécithine de tournesol, arôme naturel, poudres à lever (carbonate d’ammonium, carbonate acide de sodium), édulcorant: sucralose,', 'b', 'Magasins U', 'Gerblé', 'https://fr.openfoodfacts.org/produit/3175681105423/cookie-cacao-pepites-gerble'),
(154, 'snacks', 'BISCUITS Cuillers Bio', 'Sucre de canne roux**, farine de _blé_ (contient _gluten_)**, _œufs_* * 34%, jaunes d\'oeufs** 2 % sirop de sucre inverti**, sel, arôme naturel de vanille, blanc d\'_œufs_ en poudre**, acidifiant : tartrates de potassium, épaississant : gomme xanthane. *Biologiques.', 'd', 'Auchan', 'Auchan', 'https://fr.openfoodfacts.org/produit/3596710356096/biscuits-cuillers-bio-auchan'),
(155, 'cheeses', 'Paturage', 'Lait pasteurisé (France), sel, ferments lactiques, coagulant. INFORMATIONS:', 'd', 'Intermarché', 'Paturages', 'https://fr.openfoodfacts.org/produit/3250392224981/paturage-paturages'),
(156, 'cheeses', 'Saveur d\'Antan (20% MG)', '_lait_ de vache pasteurisé, sel, ferments lactiques et d\'affinage (dont _lait_), présure.', 'd', 'Auchan', 'Sans marque,Chavegrand', 'https://fr.openfoodfacts.org/produit/3365500000033/saveur-d-antan-20-mg-sans-marque'),
(157, 'desserts', 'Tiramisu', 'mascarpone 21,3% [crème, lait, correcteur d\'acidité (acide lactique) (lait)], café 20% (eau, sirop de glucose, sucre, alcool, café instantané 0,5%, extrait de café), eau, sirop de glucose, génoise 7,8% [farine de blé, ceuf de poules élevées en plein air, sucre, émulsifiant (mono - et diglycérides d\'acides gras), poudres à lever (diphosphates, carbonates de sodium)], lait écrémé en poudre, sucre, oeuf de poules élevées en plein air, vin Marsala 1,4%, poudre de cacao 1,1%, alcool, fibre d\'agrumes, épaississant (carraghénanes), émulsifiant (mono - et diglycérides d\'acides gras). Degré d\'alcool: 1,4%.', 'd', 'Delhaize', 'Delhaize', 'https://fr.openfoodfacts.org/produit/5400112138304/tiramisu-delhaize');

-- --------------------------------------------------------

--
-- Structure de la table `product_id`
--

DROP TABLE IF EXISTS `product_id`;
CREATE TABLE IF NOT EXISTS `product_id` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_user` int(11) DEFAULT NULL,
  `id_product` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_user` (`id_user`),
  KEY `id_product` (`id_product`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `product_id`
--

INSERT INTO `product_id` (`id`, `id_user`, `id_product`) VALUES
(1, 1, 46),
(2, 1, 11);

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(155) NOT NULL,
  `password` varchar(155) NOT NULL,
  `mail` varchar(155) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pseudo` (`pseudo`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id`, `pseudo`, `password`, `mail`) VALUES
(1, 'hugo', 'stream03', 'hugo.com'),
(2, 'jack', 'skely92', 'jack@gmail.com ');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
